import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Home/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "al-hadith",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div>
          <Navbar />
        </div>
        {children}
      </body>
    </html>
  );
}
